seed_everything: null

ckpt_path: null

data:
  class_path: "hf_utils.CIFAR10DataModule"
  init_args:
    data_dir: "run/data/"
    img_size: [224, 224]
    img_mean: [0.485, 0.456, 0.406]
    img_std: [0.229, 0.224, 0.225]
    tiny: false
    random_state: 42
    batch_size: 32
    num_workers: 0

model:
  class_path: "hf_utils.LightningImgClassif"
  init_args:
    model_name: "microsoft/resnet-18"
    data_dir: "run/data/"
    num_labels: 10
    lr: 1e-04

trainer:
  accelerator: "cpu"
  max_epochs: 100
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  logger:
    class_path: "lightning.pytorch.loggers.TensorBoardLogger"
    init_args:
      save_dir: "run/"
      name: "transfer"
      version: null
    # class_path: "lightning.pytorch.loggers.MLFlowLogger"
    # init_args:
    #   experiment_name: "transfer"
    #   run_name: null
    #   save_dir: "run/mlruns/"
    #   log_model: true
  callbacks:
    - class_path: "lightning.pytorch.callbacks.LearningRateMonitor"
      init_args:
        logging_interval: null
    - class_path: "lightning.pytorch.callbacks.ModelCheckpoint"
      init_args:
        filename: "best"
        monitor: "val_loss"
        mode: "min"
        save_top_k: 1
    - class_path: "lightning.pytorch.callbacks.ModelCheckpoint"
      init_args:
        filename: "{epoch}"
        save_top_k: -1
        every_n_epochs: 1
        save_last: true
    # - class_path: "lightning.pytorch.callbacks.ModelCheckpoint"
    #   init_args:
    #     filename: "{step}"
    #     save_top_k: -1
    #     every_n_train_steps: 1
    #     save_last: false

